#ifndef __fdd_gpu__
#define __fdd_gpu__
/*****
  command line parser interface -- generated by clig 
  (http://wsd.iitb.fhg.de/~geg/clighome/)

  The command line parser `clig':
  (C) 1995-2004 Harald Kirsch (clig@geggus.net)
*****/

#ifdef __cplusplus
extern "C" {
#endif

typedef struct s_Cmdline {
  /***** -lodm: The lowest dispersion measure to de-disperse (cm^-3 pc) */
  char lodmP;
  double lodm;
  int lodmC;
  /***** -hidm: The highest dispersion measure to use(cm^-3 pc) */
  char hidmP;
  double hidm;
  int hidmC;
  /***** -pwidth: Pulse width (in ms) used to calculate DM values */
  char pwidthP;
  double pwidth;
  int pwidthC;
  /***** -downsamp: The number of neighboring bins to co-add */
  char downsampP;
  int downsamp;
  int downsampC;
  /***** -numdms: Number of dm values */
  char numdmsP;
  int numdms;
  int numdmsC;
  /***** -dmstep: DM step size */
  char dmstepP;
  double dmstep;
  int dmstepC;
  int dmstepW;
  /***** -fftout: Output the FFT coefficients instead of time series data. */
  char fftoutP;
  /***** -multout: Output individual files containing time series or fft coefficients for different DM values. */
  char multoutP;
  /***** -cleanout: Output individual files containing time series or fft coefficients for different DM values. */
  char cleanoutP;
  /***** -o: Root of the output file names */
  char outfileP;
  char* outfile;
  int outfileC;
  /***** -numfits: Number of fits files to process */
  char numfitsP;
  int numfits;
  int numfitsC;
  /***** uninterpreted command line parameters */
  int argc;
  /*@null*/char **argv;
  /***** the whole command line concatenated */
  char *full_cmd_line;
} Cmdline;

  extern Cmdline cmd;

  extern char *Program;
  extern void usage(void);
  extern /*@shared*/Cmdline *parseCmdline(int argc, char **argv);

  extern void showOptionValues(void);

#ifdef __cplusplus
}
#endif

#endif

